### ISSUE TITLE
Dropdown focus with long list of notebooks

### ISSUE THREAD

**Issue by leakymemory** [OneNoteDev/OneNotePicker-JS#12]
When we open the dropdown, the visible list is always set to the top. In other words, if I have a large number of notebooks in my list, and if the one I have currently selected is towards the bottom, I need to scroll down each time to set the destination to a different section.

To me, it would be more intuitive to make sure that the selected section is visible when I expand the dropdown.

**Comment by RedTn** [comment]
Using Chrome, seems to be working as you intended in your latest DEV 3.6.1 when I forked it, but hasn't been pushed to production yet. Maybe the script you're referencing in the web clipper is an older version? Looks like it was patched [here](https://github.com/OneNoteDev/OneNotePicker-JS/commit/72242e461657168c5d8bb43ffcd88ea38b8eaf2b)

**Comment by leakymemory** [comment]
You're right.  This was fixed.
